server:
  port: 8081

# dadtabase 연동
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/member
    username: test
    password: test

  jpa:
    database: postgresql
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update